apiVersion: v1
kind: Service
metadata:
  name: execution-sandbox-svc
  namespace: qlp-production
spec:
  selector:
    app: execution-sandbox
  ports:
  - port: 8004
    targetPort: 8004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-sandbox
  namespace: qlp-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: execution-sandbox
  template:
    metadata:
      labels:
        app: execution-sandbox
    spec:
      serviceAccountName: execution-controller
      containers:
      - name: execution-sandbox
        image: qlpregistry.azurecr.io/qlp/execution-sandbox:latest
        ports:
        - containerPort: 8004
        env:
        - name: SERVICE_NAME
          value: "execution-sandbox"
        - name: PORT
          value: "8004"
        - name: EXECUTION_MODE
          value: "kubernetes"  # Use Kubernetes pods instead of Docker
        - name: ENABLE_RUNTIME_SELECTION
          value: "true"
        - name: KUBERNETES_NAMESPACE
          value: "qlp-production"
        - name: DEFAULT_RUNTIME_CLASS
          value: "gvisor"  # Secure by default
        envFrom:
        - configMapRef:
            name: qlp-config
        - configMapRef:
            name: execution-config
        - secretRef:
            name: qlp-secrets
        volumeMounts:
        - name: controller-code
          mountPath: /app/controller
        - name: runtime-profiles
          mountPath: /runtime-profiles
        - name: workspace
          mountPath: /workspace
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /health
            port: 8004
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8004
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: controller-code
        configMap:
          name: execution-controller-code
      - name: runtime-profiles
        configMap:
          name: runtime-profiles
      - name: workspace
        emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: execution-controller
  namespace: qlp-production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: execution-controller
  namespace: qlp-production
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec", "pods/status"]
  verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: execution-controller
  namespace: qlp-production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: execution-controller
subjects:
- kind: ServiceAccount
  name: execution-controller
  namespace: qlp-production