kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 8000
    protocol: TCP
  - containerPort: 30001
    hostPort: 8001
    protocol: TCP
  - containerPort: 30002
    hostPort: 8002
    protocol: TCP
  - containerPort: 30003
    hostPort: 8003
    protocol: TCP
  - containerPort: 30004
    hostPort: 8004
    protocol: TCP
  - containerPort: 30088
    hostPort: 8088
    protocol: TCP
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP