# Railway configuration for QLP services

[build]
builder = "dockerfile"

[deploy]
startCommand = "docker-entrypoint.sh"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
healthcheckTimeout = 10
sleepApplication = false

# Service-specific configurations
[services.orchestrator]
port = 8000
cpu = 0.5
memory = "1Gi"

[services.agent-factory]
port = 8001
cpu = 1.0
memory = "2Gi"

[services.validation-mesh]
port = 8002
cpu = 0.5
memory = "1Gi"

[services.vector-memory]
port = 8003
cpu = 0.5
memory = "1Gi"

[services.execution-sandbox]
port = 8004
cpu = 1.0
memory = "2Gi"
privileged = true

[services.temporal-worker]
cpu = 1.0
memory = "2Gi"
restartPolicyType = "always"